name: hook

on:
  schedule:
    # At 05:00 on every day-of-month from 1 through 25 in December
    # (5:00 AM UTC is midnight EST)
    - cron: "0 5 1-25 12 *"

jobs:
  hook:
    runs-on: ubuntu-latest
    name: Send slack webhook
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run webhook
        run: SLACK_URL=${{ secrets.SLACK_URL }} python main.py
